// English mirror of es.js. Spanish names stay Spanish; samples stay samples.

const en = {
  meta: {
    title: "Diagnostikare · Your health, in the hands of people you can name",
    teamTitle: "Our team · Diagnostikare",
  },
  sample: "Sample",
  photo: "Photo",
  nav: {
    how: "How it works",
    team: "Team",
    impact: "Impact",
    orgs: "Organizations",
    patient: "I'm a patient",
    book: "Book a call",
    menu: "Menu",
    close: "Close",
    skip: "Skip to content",
    langLabel: "Language",
  },
  hero: {
    h1: "Your health, in the hands of people you can name.",
    lead:
      "Message us on WhatsApp. CORA asks the right questions in minutes, and when you need a person, someone from our team picks up: doctors, nutritionists and psychologists, all licensed here in Mexico.",
    cta: "Book a call",
    ctaTeam: "Meet the team",
    patientLine: "Already covered through your employer?",
    patientLink: "Message us on WhatsApp",
    since: "Covering more than 500,000 people since 2019.",
    sinceSource: "Source: Diagnostikare, [year]",
    photo: {
      subject: "Dra. Nombre Apellido, general practitioner",
      brief: "Answering a WhatsApp in the office, mid-conversation. Morning light, unposed, at eye level.",
    },
    slip: {
      when: "Today, 07:49",
      reasonLabel: "Reason",
      reason: "Sore throat and fever",
      attendedBy: "Seen by",
      name: "Dra. Nombre Apellido",
      role: "General medicine",
      license: "License no. 0000000",
      stamp: "Seen",
      stampSub: "Diagnostikare",
    },
  },
  team: {
    h2: "The people who answer.",
    lead:
      "General practitioners and internists, nutritionists and clinical psychologists. Each with their license number on show, so you can look it up in Mexico's national registry if you like.",
    quote: "The first thing I do is read everything you told CORA, so I never ask you the same thing twice.",
    quoteBy: "Dra. Nombre Apellido, general medicine",
    toneNote: "Tone example. Each person writes their own line.",
    all: "Meet the whole team",
    verify: "Check a license with the SEP",
  },
  disciplines: {
    med: "Medicine",
    nut: "Nutrition",
    psi: "Psychology",
    cora: "CORA",
  },
  people: [
    {
      id: "p1", discipline: "med", title: "Dra.", role: "General medicine", tone: "sage",
      brief: "Portrait in the Mexico City office, phone in hand.",
      quote: "I read everything you told CORA before I say hello.",
    },
    {
      id: "p2", discipline: "nut", title: "Lic.", role: "Clinical nutrition", tone: "nut",
      brief: "In the office kitchen, mid-chat, no white coat.",
      quote: "I won't ask you to give up tortillas. We'll work out how many.",
    },
    {
      id: "p3", discipline: "psi", title: "Psic.", role: "Clinical psychology", tone: "psi",
      brief: "By a window, soft afternoon light.",
      quote: "You can write to us whenever you feel ready to.",
    },
    {
      id: "p4", discipline: "med", title: "Dr.", role: "Internal medicine", tone: "sage",
      brief: "Standing in the hallway, reviewing a case on a tablet.",
      quote: "If your case needs a specialist, I'll tell you which one and why.",
    },
    {
      id: "p5", discipline: "med", title: "Dra.", role: "Family medicine", tone: "sage",
      brief: "Seated, on a video call with a patient, in profile.",
      quote: "I've known a lot of my patients since their very first message.",
    },
    {
      id: "p6", discipline: "psi", title: "Mtra.", role: "Psychotherapy", tone: "psi",
      brief: "In the meeting room, laughing with the team.",
      quote: "Talking to someone doesn't have to wait until things get worse.",
    },
    {
      id: "p7", discipline: "nut", title: "Lic.", role: "Nutrition and diabetes", tone: "nut",
      brief: "Going over a glucose reading with a patient, patient's back to camera.",
      quote: "Your plan has to fit your shift, or it won't work.",
    },
    {
      id: "p8", discipline: "med", title: "Dr.", role: "General medicine", tone: "sage",
      brief: "Afternoon shift, answering WhatsApp from his desk.",
      quote: "I'd rather ask one question too many than leave you unsure.",
    },
    {
      id: "p9", discipline: "psi", title: "Psic.", role: "Workplace health and NOM-035", tone: "psi",
      brief: "With a group of employees at a plant, after a session.",
      quote: "Work stress gets treated too, and the earlier the better.",
    },
    {
      id: "p10", discipline: "med", title: "Dra.", role: "Medical director", tone: "sage",
      brief: "In her office, looking at the camera. The team's only formal portrait.",
      quote: "I review the clinical protocols CORA uses to ask its questions.",
    },
  ],
  journey: {
    h2: "A warehouse worker's first consult, minute by minute.",
    lead:
      "She works in the warehouse of a client company in Tultitlán and has IMSS. This is her first consult with us, the way it reads in her record.",
    note: "Illustrative story. We'll tell it with a real patient, with her consent.",
    colTime: "Time",
    colWhat: "What happened",
    colWho: "Who",
    prepared: "Prepared by",
    attended: "Seen by",
    rows: [
      {
        time: "07:40",
        title: "She writes on her break.",
        text: "From the phone she already has, with no app to download.",
        artifact: { type: "bubble", from: "patient", text: "Hi, my throat's been hurting since yesterday and now I have a fever." },
        who: { kind: "cora", name: "CORA", role: "Clinical assistant" },
      },
      {
        time: "07:43",
        title: "CORA asks what a doctor would ask.",
        text: "How high is the fever? Since when? Any trouble breathing? From her answers CORA builds the case and sees that this time a doctor should take a look.",
        artifact: { type: "chips", items: ["Fever of 38.4 °C", "Sore throat", "Since yesterday", "Breathing normally"] },
        tag: "Under an ISO 13485 certified quality system",
        who: { kind: "cora", name: "CORA Triage", role: "Clinical assessment" },
      },
      {
        time: "07:49",
        title: "A doctor takes the case.",
        text: "She arrives with the full context. The patient doesn't have to tell her story twice.",
        artifact: { type: "bubble", from: "doctor", text: "Good morning, I'm Dra. [Apellido], a general practitioner. I've read what you told CORA. Can I video call you in five minutes?" },
        who: { kind: "med", name: "Dra. Nombre Apellido", role: "General medicine", license: "License no. 0000000", stamp: true },
        handoff: true,
      },
      {
        time: "07:56",
        title: "A video consult, from the warehouse.",
        text: "Fifteen minutes. The prescription and lab order go into her care plan, which she can open whenever she likes.",
        artifact: { type: "plan", items: ["Prescription", "Lab order", "Follow-up on Thursday"] },
        who: { kind: "med", name: "Dra. Nombre Apellido", role: "General medicine" },
      },
      {
        time: "Thursday, 09:10",
        title: "The doctor checks in on her.",
        text: "Nobody is left halfway: the follow-up arrives on its own, in the same chat.",
        artifact: { type: "thread", items: [
          { from: "doctor", text: "How are you feeling this morning? Has the fever come down?" },
          { from: "patient", text: "Yes, much better. Thank you, doctor." },
        ] },
        who: { kind: "med", name: "Dra. Nombre Apellido", role: "General medicine" },
      },
      {
        time: "A month later",
        title: "She checks her blood pressure with her phone camera, and talks to nutrition.",
        text: "CORA Vitals reads her vital signs in under a minute. The reading goes into her history, and the nutritionist uses it to build her plan."
        ,note: "Readings are for information and don't replace a medical evaluation.",
        artifact: { type: "vitals", items: [["Blood pressure", "Being tracked"], ["Heart rate", "In range"]] },
        who: { kind: "nut", name: "Lic. Nombre Apellido", role: "Clinical nutrition", license: "License no. 0000000" },
      },
    ],
    privacy: "Her employer never sees her record. HR only sees aggregate, anonymous data.",
    patientLabel: "Patient",
  },
  impact: {
    statement: "of the people we care for accessed a health service for the first time.",
    number: "89%",
    source:
      "Measured by 60 Decibels, an independent impact measurement firm. It places us in the top 20% of its global health benchmark.",
    story: {
      subject: "One of those people, with their consent",
      brief: "At home or at work, never in a studio. Half-length portrait, natural light.",
      label: "Real story to come",
      template: "“Before, when I got sick, [what they did]. The first time a doctor answered, [what changed].”",
      byline: "[Name], [age] · [city] · A real person, with their consent · Story to be confirmed",
    },
    rows: [
      { value: "53%", label: "report a better quality of life", source: "60 Decibels" },
      { value: "54%", label: "report better health in their family", source: "60 Decibels" },
      { value: "34%", label: "spend less on health", source: "60 Decibels" },
    ],
    gender: "First-time access is higher among women: 91%, compared with 85% of men.",
    sourceLabel: "Source",
  },
  trust: {
    intro: "Since 2019, with more than 95% retention, an NPS of 97 (the healthcare average is 58) and 48% shorter wait times.",
    introSource: "Source: Diagnostikare, [year]",
    rows: [
      {
        label: "Certifications",
        items: [
          "ISO 13485:2016 and ISO 9001:2015, by AENOR",
          "COFEPRIS criterion, letter 193300C0240119",
          "REPSE AR-220254/2026",
          "Socially Responsible Company, Cemefi",
          "Great Place to Work",
          "Newsweek, World's Best Digital Health Companies 2024",
        ],
      },
      {
        label: "Chosen by",
        items: ["Elektra", "Banco Azteca", "Liverpool", "Arcos Dorados", "Bayer", "Sandoz", "Rappi", "Iberdrola", "Totalplay", "Italika", "Neto", "TV Azteca", "Sofitel", "Kueski", "CNH", "Howden"],
      },
      {
        label: "Backed by",
        items: ["Philips Foundation", "StartUp Health", "Boehringer Ingelheim", "Plug and Play", "Global Partnerships", "Access Capital", "Builders VC"],
      },
    ],
  },
  orgs: {
    h2: "For organizations that look after a lot of people.",
    lead: "Employers, health plans and patient programs. The same team, the same way of caring.",
    rows: [
      {
        label: "Employers",
        text: "Your people have IMSS and still wait weeks for an appointment. With us they message on WhatsApp today, and someone from our team follows up until the case is closed.",
        detail: "They sign up over WhatsApp, with nothing to download. You receive aggregate reports and NOM-035 compliance.",
      },
      {
        label: "Health plans and brokers",
        text: "A first point of contact that resolves over chat what can be resolved, and refers the rest with the case already written up.",
      },
      {
        label: "Patient programs",
        text: "Follow-up between visits, with people who already know the case, so nobody drops their treatment halfway.",
        detail: "Prescriptions, lab work and appointment reminders live in a plan the patient can open whenever they like.",
      },
    ],
    seesTitle: "What HR sees",
    sees: "Aggregate, anonymous wellbeing trends, NOM-035 compliance and risk reports.",
    neverTitle: "What HR never sees",
    never: "Any one person's record, consults or readings.",
  },
  booking: {
    h2: "Tell us who you'd like to look after.",
    replierName: "Nombre Apellido",
    replierRole: "Partnerships, Diagnostikare",
    replierBrief: "Portrait of the person who answers requests.",
    lead: "Nombre Apellido from our partnerships team will get back to you within 24 business hours.",
    fields: {
      name: "Your name",
      email: "Work email",
      phone: "Phone (optional)",
      org: "Organization (optional)",
      type: "Type of organization",
      size: "How many people do you want to cover? (optional)",
      choose: "Choose an option",
    },
    types: ["Company or organization", "Health plan, broker or intermediary", "Patient program"],
    sizes: ["Fewer than 200", "200 to 1,000", "1,000 to 10,000", "More than 10,000"],
    submit: "Book the call",
    sending: "Sending…",
    consent: "By sending this you accept our privacy notice. We only use your details to reply to you.",
    errors: {
      name: "Add your name so we know who to greet.",
      email: "Add a valid work email, for example name@company.com.",
      type: "Choose your type of organization so we can prepare the call.",
    },
    successTitle: "Done, {name}.",
    successText: "Nombre Apellido will write to {email} within 24 business hours.",
    successWa: "Prefer WhatsApp? Message us here",
    again: "Send another request",
    patient: "Are you a patient?",
    patientLink: "Message us on WhatsApp",
    demoNote: "Mockup: this form doesn't send anything.",
  },
  footer: {
    tagline: "A Mexican health and technology company. Doctors, nutritionists and psychologists who care for you on WhatsApp.",
    colCare: "Care",
    colOrgs: "Organizations",
    colCompany: "Diagnostikare",
    care: ["How it works", "Our team", "I'm a patient"],
    orgs: ["Employers", "Health plans", "Patient programs"],
    company: ["Impact", "Certifications", "Privacy notice", "Code of ethics"],
    contact: "Contact",
    whatsapp: "WhatsApp",
    legal:
      "Servicios Clínicos Inteligentes DXKARE, S.A.P.I. de C.V. provides digital medical care services under the criterion confirmed by COFEPRIS in letter 193300C0240119. REPSE registration AR-220254/2026.",
    rights: "©2026 Diagnostikare. All rights reserved.",
    mock: "Proposal mockup. People, photos and quotes are samples.",
  },
  teamPage: {
    h1: "Our care team.",
    lead: "The people who answer when you write. Each with their name, their specialty and their license number on show.",
    counts: "[N] doctors, [N] nutritionists and [N] psychologists",
    countsNote: "Figures to be confirmed with Diagnostikare.",
    filterLabel: "Filter by specialty",
    all: "Whole team",
    toneNote: "The quotes are tone examples. Each person will write their own.",
    verify: "Check license",
    howH2: "How we work with CORA.",
    how: [
      { label: "CORA asks", text: "It asks the questions of a clinical assessment, sorts out your symptoms and builds the case." },
      { label: "A person decides", text: "When it's needed, the case reaches someone on the team with the full context. If a diagnosis or a prescription is needed, a person gives it." },
      { label: "We stay with you", text: "Follow-up messages, lab work and your care plan, in the same chat where you started." },
    ],
    joinH2: "Are you a doctor, nutritionist or psychologist?",
    joinText: "We're looking for people who enjoy answering a message well at seven in the morning.",
    joinCta: "Write to us",
    verifyH: "Any license can be checked.",
    verifyText: "It's a public registry run by Mexico's Ministry of Education (SEP). Look up the name of anyone on our team.",
    verifyCta: "Open the national registry",
  },
};

export default en;
