// Spanish (México) is the primary language.
// Every person named here is a marked sample ("Nombre Apellido") until the
// client supplies real people, consent and photography. Numbers and
// certifications come from diagnostikare.com.

const es = {
  meta: {
    title: "Diagnostikare · Tu salud, en manos de personas con nombre y apellido",
    teamTitle: "Nuestro equipo · Diagnostikare",
  },
  sample: "Muestra",
  photo: "Foto",
  nav: {
    how: "Cómo funciona",
    team: "Equipo",
    impact: "Impacto",
    orgs: "Organizaciones",
    patient: "Soy paciente",
    book: "Agenda una llamada",
    menu: "Menú",
    close: "Cerrar",
    skip: "Saltar al contenido",
    langLabel: "Idioma",
  },
  hero: {
    h1: "Tu salud, en manos de personas con nombre y apellido.",
    lead:
      "Escríbenos por WhatsApp. CORA te hace las preguntas correctas en minutos y, cuando necesitas a alguien, te atiende una persona de nuestro equipo: médicos, nutriólogas y psicólogos con cédula profesional, aquí en México.",
    cta: "Agenda una llamada",
    ctaTeam: "Conoce al equipo",
    patientLine: "¿Ya tienes Diagnostikare por tu empresa?",
    patientLink: "Escríbenos por WhatsApp",
    since: "Más de 500,000 personas en cobertura desde 2019.",
    sinceSource: "Fuente: Diagnostikare, [año]",
    photo: {
      subject: "Dra. Nombre Apellido, médica general",
      brief: "Contestando un WhatsApp en el consultorio, a media conversación. Luz de mañana, sin pose, a la altura de los ojos.",
    },
    slip: {
      when: "Hoy, 07:49",
      reasonLabel: "Motivo",
      reason: "Dolor de garganta y fiebre",
      attendedBy: "Atendió",
      name: "Dra. Nombre Apellido",
      role: "Medicina general",
      license: "Céd. Prof. 0000000",
      stamp: "Atendido",
      stampSub: "Diagnostikare",
    },
  },
  team: {
    h2: "Las personas que te contestan.",
    lead:
      "Médicos generales e internistas, nutriólogas y psicólogos clínicos. Cada uno con su cédula a la vista, para que la verifiques en el Registro Nacional de Profesionistas si quieres.",
    quote: "Lo primero que hago es leer todo lo que le contaste a CORA. Así no te pregunto lo mismo dos veces.",
    quoteBy: "Dra. Nombre Apellido, medicina general",
    toneNote: "Ejemplo de tono. Cada persona escribe su propia frase.",
    all: "Conoce a todo el equipo",
    verify: "Verifica una cédula en la SEP",
  },
  disciplines: {
    med: "Medicina",
    nut: "Nutrición",
    psi: "Psicología",
    cora: "CORA",
  },
  people: [
    {
      id: "p1", discipline: "med", title: "Dra.", role: "Medicina general", tone: "sage",
      brief: "Retrato en el consultorio de CDMX, con el celular en la mano.",
      quote: "Leo todo lo que le contaste a CORA antes de saludarte.",
    },
    {
      id: "p2", discipline: "nut", title: "Lic.", role: "Nutrición clínica", tone: "nut",
      brief: "En la cocina de la oficina, platicando, sin bata.",
      quote: "No te voy a pedir que dejes las tortillas. Vamos a ver cuántas.",
    },
    {
      id: "p3", discipline: "psi", title: "Psic.", role: "Psicología clínica", tone: "psi",
      brief: "Junto a una ventana, con luz suave de tarde.",
      quote: "Aquí puedes escribir a la hora que te dé valor hacerlo.",
    },
    {
      id: "p4", discipline: "med", title: "Dr.", role: "Medicina interna", tone: "sage",
      brief: "De pie en el pasillo, revisando un caso en la tableta.",
      quote: "Si el caso necesita un especialista, te digo cuál y por qué.",
    },
    {
      id: "p5", discipline: "med", title: "Dra.", role: "Medicina familiar", tone: "sage",
      brief: "Sentada, en videollamada con un paciente, de perfil.",
      quote: "A muchos pacientes los conozco desde su primer mensaje.",
    },
    {
      id: "p6", discipline: "psi", title: "Mtra.", role: "Psicoterapia", tone: "psi",
      brief: "En la sala de juntas, riéndose con el equipo.",
      quote: "Hablar con alguien no tiene que esperar a que estés peor.",
    },
    {
      id: "p7", discipline: "nut", title: "Lic.", role: "Nutrición y diabetes", tone: "nut",
      brief: "Revisando una lectura de glucosa con una paciente, de espaldas a la cámara.",
      quote: "Tu plan tiene que caber en tu turno, si no, no sirve.",
    },
    {
      id: "p8", discipline: "med", title: "Dr.", role: "Medicina general", tone: "sage",
      brief: "Turno de la tarde, contestando WhatsApp desde su escritorio.",
      quote: "Prefiero una pregunta de más que un paciente con dudas.",
    },
    {
      id: "p9", discipline: "psi", title: "Psic.", role: "Salud laboral y NOM-035", tone: "psi",
      brief: "Con un grupo de colaboradores en una planta, después de una sesión.",
      quote: "El estrés del trabajo también se atiende, y mejor si es temprano.",
    },
    {
      id: "p10", discipline: "med", title: "Dra.", role: "Dirección médica", tone: "sage",
      brief: "En su oficina, mirando a cámara. El único retrato formal del equipo.",
      quote: "Reviso los protocolos con los que CORA hace sus preguntas.",
    },
  ],
  journey: {
    h2: "La primera consulta de una almacenista en Tultitlán, minuto a minuto.",
    lead:
      "Trabaja en el almacén de una empresa cliente y tiene IMSS. Así fue su primera consulta con nosotros, contada como queda en su expediente.",
    note: "Historia ilustrativa. La contaremos con una paciente real y con su permiso.",
    colTime: "Hora",
    colWhat: "Qué pasó",
    colWho: "Quién",
    prepared: "Preparó",
    attended: "Atendió",
    rows: [
      {
        time: "07:40",
        title: "Escribe en su descanso.",
        text: "Desde el celular que ya usa, sin bajar ninguna app.",
        artifact: { type: "bubble", from: "patient", text: "Hola, desde ayer me duele la garganta y ahorita tengo fiebre." },
        who: { kind: "cora", name: "CORA", role: "Asistente clínico" },
      },
      {
        time: "07:43",
        title: "CORA le hace las preguntas que haría un médico.",
        text: "¿Cuánta fiebre? ¿Desde cuándo? ¿Respiras bien? Con sus respuestas arma el caso y ve que esta vez sí conviene que la vea una doctora.",
        artifact: { type: "chips", items: ["Fiebre de 38.4 °C", "Dolor de garganta", "Desde ayer", "Respira bien"] },
        tag: "Con un sistema de calidad certificado ISO 13485",
        who: { kind: "cora", name: "CORA Triage", role: "Valoración clínica" },
      },
      {
        time: "07:49",
        title: "Una doctora toma el caso.",
        text: "Llega con todo el contexto. Ella no tiene que volver a contar nada.",
        artifact: { type: "bubble", from: "doctor", text: "Hola, buenos días. Soy la Dra. [Apellido], médica general. Ya leí lo que le contaste a CORA. ¿Te marco por video en cinco minutos?" },
        who: { kind: "med", name: "Dra. Nombre Apellido", role: "Medicina general", license: "Céd. Prof. 0000000", stamp: true },
        handoff: true,
      },
      {
        time: "07:56",
        title: "Consulta por video, desde el almacén.",
        text: "Quince minutos. La receta y la orden de laboratorio quedan en su plan de cuidado, que puede abrir cuando quiera.",
        artifact: { type: "plan", items: ["Receta", "Orden de laboratorio", "Seguimiento el jueves"] },
        who: { kind: "med", name: "Dra. Nombre Apellido", role: "Medicina general" },
      },
      {
        time: "Jueves, 09:10",
        title: "La doctora le escribe para ver cómo sigue.",
        text: "Nadie se queda a medias: el seguimiento llega solo, al mismo chat.",
        artifact: { type: "thread", items: [
          { from: "doctor", text: "¿Cómo amaneciste? ¿Ya bajó la fiebre?" },
          { from: "patient", text: "Ya, mucho mejor. Gracias, doctora." },
        ] },
        who: { kind: "med", name: "Dra. Nombre Apellido", role: "Medicina general" },
      },
      {
        time: "Un mes después",
        title: "Se mide la presión con la cámara del celular y platica con nutrición.",
        text: "CORA Vitals lee sus signos en menos de un minuto. La lectura queda en su historial y la nutrióloga la usa para armar su plan."
        ,note: "Las lecturas son informativas y no sustituyen una valoración médica.",
        artifact: { type: "vitals", items: [["Presión", "En seguimiento"], ["Ritmo cardiaco", "En rango"]] },
        who: { kind: "nut", name: "Lic. Nombre Apellido", role: "Nutrición clínica", license: "Céd. Prof. 0000000" },
      },
    ],
    privacy: "Su empresa nunca ve su expediente. Recursos Humanos solo ve datos agregados y anónimos.",
    patientLabel: "Paciente",
  },
  impact: {
    statement: "de las personas que atendemos accedió por primera vez a un servicio de salud.",
    number: "89%",
    source:
      "Medido por 60 Decibels, una firma independiente de medición de impacto. Nos ubica en el 20% superior de su benchmark global de salud.",
    story: {
      subject: "Una de esas personas, con su permiso",
      brief: "En su casa o en su trabajo, nunca en un estudio. Retrato de medio cuerpo, luz natural.",
      label: "Historia real por confirmar",
      template: "“Antes, cuando me enfermaba, [qué hacía]. La primera vez que me contestó un médico, [qué cambió].”",
      byline: "[Nombre], [edad] · [ciudad] · Persona real, con su permiso · Historia por confirmar",
    },
    rows: [
      { value: "53%", label: "reporta mejor calidad de vida", source: "60 Decibels" },
      { value: "54%", label: "reporta mejor salud en su familia", source: "60 Decibels" },
      { value: "34%", label: "gasta menos en salud", source: "60 Decibels" },
    ],
    gender: "El primer acceso es mayor entre mujeres: 91%, frente a 85% de los hombres.",
    sourceLabel: "Fuente",
  },
  trust: {
    intro: "Desde 2019, con una retención de más del 95%, un NPS de 97 (el promedio en salud es 58) y 48% menos tiempo de espera.",
    introSource: "Fuente: Diagnostikare, [año]",
    rows: [
      {
        label: "Certificaciones",
        items: [
          "ISO 13485:2016 e ISO 9001:2015, por AENOR",
          "Criterio COFEPRIS, oficio 193300C0240119",
          "REPSE AR-220254/2026",
          "Empresa Socialmente Responsable, Cemefi",
          "Great Place to Work",
          "Newsweek, World's Best Digital Health Companies 2024",
        ],
      },
      {
        label: "Nos eligieron",
        items: ["Elektra", "Banco Azteca", "Liverpool", "Arcos Dorados", "Bayer", "Sandoz", "Rappi", "Iberdrola", "Totalplay", "Italika", "Neto", "TV Azteca", "Sofitel", "Kueski", "CNH", "Howden"],
      },
      {
        label: "Nos respaldan",
        items: ["Philips Foundation", "StartUp Health", "Boehringer Ingelheim", "Plug and Play", "Global Partnerships", "Access Capital", "Builders VC"],
      },
    ],
  },
  orgs: {
    h2: "Para quienes cuidan la salud de mucha gente.",
    lead: "Empresas, planes de salud y programas para pacientes. Mismo equipo, misma forma de cuidar.",
    rows: [
      {
        label: "Empresas",
        text: "Tu gente tiene IMSS y aun así espera semanas por una cita. Con nosotros escribe por WhatsApp hoy y una persona del equipo le da seguimiento hasta cerrar el caso.",
        detail: "Se registran por WhatsApp, sin descargar nada. Tú recibes reportes agregados y el cumplimiento de la NOM-035.",
      },
      {
        label: "Planes de salud y brokers",
        text: "Un primer contacto que resuelve por chat lo que se puede resolver y canaliza lo demás con el caso ya armado.",
      },
      {
        label: "Programas para pacientes",
        text: "Seguimiento entre consulta y consulta, con personas que ya conocen su caso, para que nadie deje el tratamiento a la mitad.",
        detail: "Receta, estudios y recordatorios de cita quedan en un plan que el paciente abre cuando quiere.",
      },
    ],
    seesTitle: "Lo que ve Recursos Humanos",
    sees: "Tendencias de bienestar agregadas y anónimas, cumplimiento de la NOM-035 y reportes de riesgo.",
    neverTitle: "Lo que nunca ve",
    never: "El expediente, las consultas o las lecturas de una persona.",
  },
  booking: {
    h2: "Cuéntanos a quién quieres cuidar.",
    replierName: "Nombre Apellido",
    replierRole: "Alianzas, Diagnostikare",
    replierBrief: "Retrato de quien contesta las solicitudes.",
    lead: "Te contesta Nombre Apellido, de nuestro equipo de alianzas, en menos de 24 horas hábiles.",
    fields: {
      name: "Tu nombre",
      email: "Correo de trabajo",
      phone: "Teléfono (opcional)",
      org: "Organización (opcional)",
      type: "Tipo de organización",
      size: "¿A cuántas personas quieres cuidar? (opcional)",
      choose: "Elige una opción",
    },
    types: ["Empresa u organización", "Plan de salud, broker o corredor", "Programa para pacientes"],
    sizes: ["Menos de 200", "De 200 a 1,000", "De 1,000 a 10,000", "Más de 10,000"],
    submit: "Agenda la llamada",
    sending: "Enviando…",
    consent: "Al enviar aceptas nuestro aviso de privacidad. Solo usamos tus datos para contestarte.",
    errors: {
      name: "Escribe tu nombre para saber cómo saludarte.",
      email: "Escribe un correo de trabajo válido, por ejemplo nombre@empresa.com.",
      type: "Elige el tipo de organización para preparar la llamada.",
    },
    successTitle: "Listo, {name}.",
    successText: "Nombre Apellido te escribe a {email} en menos de 24 horas hábiles.",
    successWa: "¿Prefieres WhatsApp? Escríbenos aquí",
    again: "Enviar otra solicitud",
    patient: "¿Eres paciente?",
    patientLink: "Escríbenos por WhatsApp",
    demoNote: "Maqueta: el formulario no envía datos.",
  },
  footer: {
    tagline: "Empresa mexicana de salud y tecnología. Médicos, nutriólogas y psicólogos que te atienden por WhatsApp.",
    colCare: "Cuidado",
    colOrgs: "Organizaciones",
    colCompany: "Diagnostikare",
    care: ["Cómo funciona", "Nuestro equipo", "Soy paciente"],
    orgs: ["Empresas", "Planes de salud", "Programas para pacientes"],
    company: ["Impacto", "Certificaciones", "Aviso de privacidad", "Código de ética"],
    contact: "Contacto",
    whatsapp: "WhatsApp",
    legal:
      "Servicios Clínicos Inteligentes DXKARE, S.A.P.I. de C.V. presta servicios de atención médica digital conforme al criterio confirmado por COFEPRIS en el oficio 193300C0240119. Registro REPSE AR-220254/2026.",
    rights: "©2026 Diagnostikare. Todos los derechos reservados.",
    mock: "Maqueta de propuesta. Personas, fotos y frases son muestras.",
  },
  teamPage: {
    h1: "Nuestro equipo de cuidado.",
    lead: "Las personas que contestan cuando escribes. Cada una con su nombre, su especialidad y su cédula a la vista.",
    counts: "[N] médicos, [N] nutriólogas y [N] psicólogos",
    countsNote: "Cifras por confirmar con Diagnostikare.",
    filterLabel: "Filtrar por especialidad",
    all: "Todo el equipo",
    toneNote: "Las frases son ejemplos de tono. Cada persona escribirá la suya.",
    verify: "Verificar cédula",
    howH2: "Cómo trabajamos con CORA.",
    how: [
      { label: "CORA pregunta", text: "Hace las preguntas de una valoración clínica, ordena tus síntomas y arma el caso." },
      { label: "Una persona decide", text: "Cuando hace falta, el caso llega a alguien del equipo con todo el contexto. Si se necesita un diagnóstico o una receta, los da una persona." },
      { label: "Seguimos contigo", text: "Mensajes de seguimiento, estudios y tu plan de cuidado, en el mismo chat donde empezaste." },
    ],
    joinH2: "¿Eres médico, nutrióloga o psicólogo?",
    joinText: "Buscamos gente que disfrute contestar bien un mensaje a las siete de la mañana.",
    joinCta: "Escríbenos",
    verifyH: "Cualquier cédula se puede verificar.",
    verifyText: "Es un registro público de la Secretaría de Educación Pública. Busca el nombre de cualquier persona de nuestro equipo.",
    verifyCta: "Abrir el Registro Nacional de Profesionistas",
  },
};

export default es;
